=head1 NAME

certain - X509 Certificate Management Service

=head1 SYNTAX

B<certain> --help

B<certain> --daemon

B<certain> [--get] [--makecert] [--sign]


=head1 DESCRIPTION

Certain is an X509 Certificate management master-client service.  The master generates its own CA certificates, receives certificate signing requests over the network, and then signs these and pushes the signed certificates to a store.

Different store types are provided, from which clients can fetch their own and other client's certificates.

Certain will continue to re-sign certificates for clients as they expire, based on the trust set up from the initial manual certificate signing.


=head1 OPTIONS

B<-h, --help> 
      Display basic help.

B<-c, --config> 
      Configuration file to use (defaults to B</etc/certain/certain.cfg>)

B<-d, --daemon>
      Launch the certain daemon.

      Both the master and clients should run the daemon:

      On the master it creates CA certificates, starts the listening
      daemon which receives CSRs, signs and stores the resulting
      certificates.

      On clients it generates a private key and a CSR (which
      it sends to the master for signing), and checks certificate
      expiry (resending CSRs as necessary).

      Note: The master is also a client of itself.


B<-p, --pidfile>
      PID file to use (defaults to B</var/run/certain.pid>)

B<-m, --makecert>
      Create a CSR and send this to the master.

B<-g, --get>
      Receive all available certificates from the store.

B<-s, --sign>
      (On master) Sign pending requests.

=head1 FILES

/etc/certain/certain.cfg

=head1 SEE ALSO

certain.cfg(5)