#!/bin/sh
#Add the certmgr user and group
groupadd --system certmgr
useradd --system --home /etc/certmgr -c "Certmgr daemon" --gid certmgr --shell /bin/false certmgr
chown -R certmgr:certmgr /etc/certmgr

