#!/bin/sh

set -e

groupadd --system --force certain >/dev/null 2>&1
getent passwd certain >/dev/null 2>&1 || useradd --system -c "Certain daemon" --gid certain --shell /bin/false certain


for f in /etc/certain/CA /etc/certain/CA/private /etc/certain/private; do
    if ! dpkg-statoverride --list $f > /dev/null; then
       dpkg-statoverride --update --add certain certain 0700 $f
    fi
done

for f in /etc/certain /etc/certain/CSRCache /etc/certain/certs /var/log/certain /var/run/certain; do
    if ! dpkg-statoverride --list $f > /dev/null; then
       dpkg-statoverride --update --add certain certain 0755 $f
    fi
done


for f in /etc/certain/certain.cfg; do
    if ! dpkg-statoverride --list $f > /dev/null; then
        dpkg-statoverride --update --add certain certain 644 $f
    fi
done

# Copied from dh_pysupport generated postinst
if which update-python-modules >/dev/null 2>&1; then
        update-python-modules  certain.public
fi

#DEBHELPER#
